/**
 * Per-building narrative overlays for native campaign encounters.
 * Topology matches B01 skeleton (shared cell graph); copy reframes read/commit/payoff per LEVELS_PLAN matrix.
 *
 * `shellTieIn` (B02–B12) must explain how the live macro shell from `CAMPAIGN_LAYOUT_BY_BN` in levelSequences.js
 * lines up with zone doors, spawn mirroring, and authored sub-room kits so design intent stays traceable in data.
 */

/** @type {Record<number, { shellTieIn?: string, rooms: Record<string, object>, floorplanSpaces?: Record<string, object> }>} */
export const NATIVE_CAMPAIGN_ENCOUNTER_NARRATIVE = {
  2: {
    shellTieIn:
      'Grand lobby shell (layout 1): mirrored zone doors and interior thresholds swap which flank feeds the first wedge—sequence route paint and spawns flip with it, so the east gallery / security relay read stays honest to door geometry.',
    rooms: {
      dock_intake: {
        label: 'Grand atrium',
        intent: 'read_and_pick_route',
        physicalIntent:
          'Formal triple lane: concierge desk read center, west salon pocket, east security compression toward mid.',
        lightingMood: 'chandelier_warm_marble',
      },
      west_service_connector: {
        label: 'West salon pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Quiet pocket off the marble bulkhead; low ceiling before the relay threshold.',
        lightingMood: 'sconce_strip_cool',
      },
      east_flank_connector: {
        label: 'East security approach',
        intent: 'flank_pressure',
        physicalIntent: 'Glass mullion compression toward the mid vestibule; concierge sightline risk.',
        lightingMood: 'accent_gold_edge',
      },
      mid_lane_center: {
        label: 'Lobby spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Center circulation plate between zone doors; elevator bank read to the cage.',
        lightingMood: 'neutral_marble_fill',
      },
      mid_lane_west: {
        label: 'West vestibule wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Narrow wedge before the security relay; partition kink breaks axis.',
        lightingMood: 'cool_security_fill',
      },
      alarm_relay_room: {
        label: 'Security relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Concierge security desk + panel; offset door breaks head-on entry from spine.',
        lightingMood: 'amber_console_pulse',
      },
      drum_lane: {
        label: 'East gallery lane',
        intent: 'flank_enfilade',
        physicalIntent: 'East gallery with planters; lateral pressure on the security relay.',
        lightingMood: 'shadow_gallery',
      },
      relay_cage: {
        label: 'Salon cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature double-height read framed by mezzanine rail and glass cage.',
        lightingMood: 'high_contrast_atrium',
      },
      foreman_cage: {
        label: 'Mezzanine office',
        intent: 'overwatch_pick',
        physicalIntent: 'Mezzanine office overlooking the salon cage; glass commit to drop read.',
        lightingMood: 'warm_office_overlook',
      },
    },
    floorplanSpaces: {
      dock_intake: {
        physicalIntent: 'Formal atrium triple lane; marble threshold frames breach into mid spine.',
      },
      west_service_connector: { physicalIntent: 'West salon pocket strip along bulkhead.' },
      east_flank_connector: { physicalIntent: 'East security compression before mid door.' },
      mid_lane_center: { physicalIntent: 'Lobby spine between front atrium and back salon cage.' },
      mid_lane_west: { physicalIntent: 'Vestibule wedge before security relay.' },
      alarm_relay_room: { physicalIntent: 'Security desk + panel anchor; offset internal door.' },
      drum_lane: { physicalIntent: 'East gallery lateral lane.' },
      relay_cage: { physicalIntent: 'Signature salon cage arena under mezzanine rail.' },
      foreman_cage: { physicalIntent: 'Mezzanine office glass overlook into cage.' },
    },
  },
  3: {
    shellTieIn:
      'Lobby shell (layout 1) mirrors the industrial door pair against B01: VIP glass and booth relay still anchor ME/MW, but the first spawn aisle pressure rotates with the shell so the sunken pit commit matches the opened flank door.',
    rooms: {
      dock_intake: {
        label: 'Vestibule & coat',
        intent: 'read_and_pick_route',
        physicalIntent: 'Low-ceiling vestibule opening to pit read: bar left, VIP glass right, center advance.',
        lightingMood: 'violet_neon_edge',
      },
      west_service_connector: {
        label: 'Bar pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Tight bar pocket along west wall; bottle shelves as vertical noise.',
        lightingMood: 'bar_top_glow',
      },
      east_flank_connector: {
        label: 'VIP glass approach',
        intent: 'flank_pressure',
        physicalIntent: 'Compressed approach toward one-way glass; strobes at threshold.',
        lightingMood: 'strobe_cyan',
      },
      mid_lane_center: {
        label: 'Dance floor spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Open dance spine between zone doors; sub bass implied by wide center plate.',
        lightingMood: 'floor_haze_neutral',
      },
      mid_lane_west: {
        label: 'Backstage wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Service wedge before booth relay; cable trays overhead.',
        lightingMood: 'uv_fill',
      },
      alarm_relay_room: {
        label: 'Booth relay',
        intent: 'objective_and_hold',
        physicalIntent: 'DJ booth style relay; panel offset from center axis for peek lanes.',
        lightingMood: 'console_amber',
      },
      drum_lane: {
        label: 'Amp corridor',
        intent: 'flank_enfilade',
        physicalIntent: 'East amp stack lane; lateral flank on booth.',
        lightingMood: 'shadow_strip_red',
      },
      relay_cage: {
        label: 'VIP pit cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature pit cage; glass rail read and hazard strip framing.',
        lightingMood: 'pit_spot_hot',
      },
      foreman_cage: {
        label: 'VIP mezz',
        intent: 'overwatch_pick',
        physicalIntent: 'Raised VIP rail read down into pit cage.',
        lightingMood: 'vip_warm_pool',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Club vestibule feeding pit read; VIP glass and bar pocket split first pressure.' },
      west_service_connector: { physicalIntent: 'West bar pocket; bottle shelves as vertical noise before booth relay.' },
      east_flank_connector: { physicalIntent: 'VIP glass approach compressed toward mid door.' },
      mid_lane_center: { physicalIntent: 'Open dance spine between zone doors; sub-bass wide commit plate.' },
      mid_lane_west: { physicalIntent: 'Backstage wedge before booth relay; cable trays overhead.' },
      alarm_relay_room: { physicalIntent: 'DJ-booth relay desk + panel; offset door for peek lanes.' },
      drum_lane: { physicalIntent: 'East amp-stack gallery; lateral flank on booth.' },
      relay_cage: { physicalIntent: 'VIP pit cage under rail; mirror split and side glass kit.' },
      foreman_cage: { physicalIntent: 'VIP mezz rail read down into pit cage.' },
    },
  },
  4: {
    shellTieIn:
      'Dock shell (layout 0) keeps B01-classic door columns: penthouse roof bridge, sunken tier, and helipad approach stay aligned with the same cargo-axis wedge rhythm the encounter graph assumes.',
    rooms: {
      dock_intake: {
        label: 'Private gallery',
        intent: 'read_and_pick_route',
        physicalIntent: 'Gallery read across sunken tier: art west, wine east, center commit to spine.',
        lightingMood: 'gallery_soft_spot',
      },
      west_service_connector: {
        label: 'Art pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'West pocket along gallery wall; low partitions as soft cover.',
        lightingMood: 'track_warm',
      },
      east_flank_connector: {
        label: 'Wine approach',
        intent: 'flank_pressure',
        physicalIntent: 'East compression past cellar door read toward drum lane.',
        lightingMood: 'cellar_amber',
      },
      mid_lane_center: {
        label: 'Living spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Long living spine over sunken tier; glass curtain wall preview to back.',
        lightingMood: 'sunset_fill',
      },
      mid_lane_west: {
        label: 'Study wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Study wedge before executive relay desk.',
        lightingMood: 'desk_pool',
      },
      alarm_relay_room: {
        label: 'Executive relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Exec desk + smart home panel; offset door for axis break.',
        lightingMood: 'panel_cool_pulse',
      },
      drum_lane: {
        label: 'Terrace lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Terrace planter lane; enfilade on relay.',
        lightingMood: 'terrace_shadow',
      },
      relay_cage: {
        label: 'Helipad approach cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature cage before helipad run; glass and hazard framing.',
        lightingMood: 'twilight_contrast',
      },
      foreman_cage: {
        label: 'Owner office',
        intent: 'overwatch_pick',
        physicalIntent: 'Owner office overlook into cage; city read beyond glass.',
        lightingMood: 'city_backlight',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Private gallery across sunken tier; art west, wine east, center spine commit.' },
      west_service_connector: { physicalIntent: 'West art pocket along gallery wall; soft partition rhythm.' },
      east_flank_connector: { physicalIntent: 'East wine approach compressed past cellar read toward drum.' },
      mid_lane_center: { physicalIntent: 'Living spine over tier; glass preview toward helipad cage.' },
      mid_lane_west: { physicalIntent: 'Study wedge before executive relay desk.' },
      alarm_relay_room: { physicalIntent: 'Executive desk + smart-home panel; offset door breaks axis.' },
      drum_lane: { physicalIntent: 'Terrace planter lane; enfilade on relay.' },
      relay_cage: { physicalIntent: 'Helipad approach cage; suite glass and crossing threshold kit.' },
      foreman_cage: { physicalIntent: 'Owner office overlook into cage; city backlight beyond glass.' },
    },
  },
  5: {
    shellTieIn:
      'Lobby shell (layout 1): triage and nurse-relay beats inherit mirrored thresholds—pick the supply pocket read first if you want a clean line into ICU without fighting the door-handedness the geometry opened on.',
    rooms: {
      dock_intake: {
        label: 'Triage court',
        intent: 'read_and_pick_route',
        physicalIntent: 'Clinical triage court: west supply, center gurney axis, east fast corridor.',
        lightingMood: 'clinical_6500k',
      },
      west_service_connector: {
        label: 'Supply pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Supply pocket; cabinet rhythm as cover.',
        lightingMood: 'cool_supply',
      },
      east_flank_connector: {
        label: 'Fast corridor mouth',
        intent: 'flank_pressure',
        physicalIntent: 'Fast corridor compression toward mid sterile door.',
        lightingMood: 'exit_green_bias',
      },
      mid_lane_center: {
        label: 'Ward spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Ward spine between zones; nurse desk read.',
        lightingMood: 'neutral_clinical',
      },
      mid_lane_west: {
        label: 'Charting wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Charting wedge before nurse relay.',
        lightingMood: 'fill_soft',
      },
      alarm_relay_room: {
        label: 'Nurse relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Nurse station + alarm interconnect; offset door.',
        lightingMood: 'alarm_soft_pulse',
      },
      drum_lane: {
        label: 'Equipment lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Equipment cart lane; lateral flank on relay.',
        lightingMood: 'shadow_corridor',
      },
      relay_cage: {
        label: 'ICU lock',
        intent: 'signature_arena',
        physicalIntent: 'ICU / surgery threshold cage; glass and hazard strip.',
        lightingMood: 'sterile_high_contrast',
      },
      foreman_cage: {
        label: 'Observation',
        intent: 'overwatch_pick',
        physicalIntent: 'Observation glass down into ICU cage.',
        lightingMood: 'observation_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Clinical triage court; supply west, fast corridor east, gurney center axis.' },
      west_service_connector: { physicalIntent: 'West supply pocket; cabinet rhythm as soft cover.' },
      east_flank_connector: { physicalIntent: 'East fast corridor mouth compressed toward mid sterile door.' },
      mid_lane_center: { physicalIntent: 'Ward spine between zones; nurse desk read mid plate.' },
      mid_lane_west: { physicalIntent: 'Charting wedge before nurse relay threshold.' },
      alarm_relay_room: { physicalIntent: 'Nurse station + alarm interconnect; offset door for clinical pinch.' },
      drum_lane: { physicalIntent: 'Equipment cart lane; lateral flank on nurse relay.' },
      relay_cage: { physicalIntent: 'ICU / surgery lock cage; observation glass and hazard strip.' },
      foreman_cage: { physicalIntent: 'Observation glass down into ICU cage.' },
    },
  },
  6: {
    shellTieIn:
      'Dock shell (layout 0): subway turnstile fiction, track pit verticality, and ticket-hall kits all assume classic cargo-axis doors—relay closet and tunnel cage payoffs stay synchronized with unmirrored zone flow.',
    rooms: {
      dock_intake: {
        label: 'Turnstile mezz',
        intent: 'read_and_pick_route',
        physicalIntent: 'Turnstile read over track pit: vendor west, express east, center stairs commit.',
        lightingMood: 'fluorescent_tunnel',
      },
      west_service_connector: {
        label: 'Vendor pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Vendor pocket along tile wall; narrow return.',
        lightingMood: 'cool_kiosk',
      },
      east_flank_connector: {
        label: 'Express flank',
        intent: 'flank_pressure',
        physicalIntent: 'Express corridor compression toward platform door.',
        lightingMood: 'amber_platform_edge',
      },
      mid_lane_center: {
        label: 'Platform spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Platform spine between zone doors; tactile strip centerline.',
        lightingMood: 'platform_neutral',
      },
      mid_lane_west: {
        label: 'Service wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Service wedge before relay closet.',
        lightingMood: 'service_fill',
      },
      alarm_relay_room: {
        label: 'Relay closet',
        intent: 'objective_and_hold',
        physicalIntent: 'SCADA style relay; panel offset for subway pinch.',
        lightingMood: 'relay_blink',
      },
      drum_lane: {
        label: 'Track-adjacent lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Track-adjacent lane; train rumble implied lateral pressure.',
        lightingMood: 'tunnel_shadow',
      },
      relay_cage: {
        label: 'Tunnel cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature tunnel threshold cage before exit run.',
        lightingMood: 'tunnel_end_hot',
      },
      foreman_cage: {
        label: 'Signal box',
        intent: 'overwatch_pick',
        physicalIntent: 'Signal box overlook into tunnel cage.',
        lightingMood: 'signal_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Turnstile mezz over track pit; vendor west, express east, center stairs commit.' },
      west_service_connector: { physicalIntent: 'Vendor pocket along tile wall; narrow return before relay closet.' },
      east_flank_connector: { physicalIntent: 'Express flank compressed toward platform mid door.' },
      mid_lane_center: { physicalIntent: 'Platform spine; tactile strip centerline between watertight reads.' },
      mid_lane_west: { physicalIntent: 'Service wedge before SCADA relay closet.' },
      alarm_relay_room: { physicalIntent: 'Relay closet desk + hardened panel; offset door for subway pinch.' },
      drum_lane: { physicalIntent: 'Track-adjacent lane; train rumble implied lateral pressure.' },
      relay_cage: { physicalIntent: 'Tunnel switch cage before exit run; pipe kit and switch corridor.' },
      foreman_cage: { physicalIntent: 'Signal box overlook into tunnel cage.' },
    },
  },
  7: {
    shellTieIn:
      'Dock shell (layout 0): companionway and bridge-wing vertical reads stay keyed to the original threshold pair—starboard lane enfilade and engine hatch cage still resolve against the unmirrored door schedule.',
    rooms: {
      dock_intake: {
        label: 'Stern reception',
        intent: 'read_and_pick_route',
        physicalIntent: 'Narrow teak reception: galley west, sun deck east, center commit along hull read.',
        lightingMood: 'sun_deck_wash',
      },
      west_service_connector: {
        label: 'Galley pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Galley service pocket; brass rail and low headroom.',
        lightingMood: 'below_deck_cool',
      },
      east_flank_connector: {
        label: 'Sun deck approach',
        intent: 'flank_pressure',
        physicalIntent: 'Sun deck approach compressed to mid companionway.',
        lightingMood: 'bright_salt_air',
      },
      mid_lane_center: {
        label: 'Companionway',
        intent: 'commit_or_rotate',
        physicalIntent: 'Companionway spine; helm door read forward.',
        lightingMood: 'teak_neutral',
      },
      mid_lane_west: {
        label: 'Port wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Port wedge before nav relay.',
        lightingMood: 'cabin_fill',
      },
      alarm_relay_room: {
        label: 'Nav relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Nav stack + alarm interconnect; offset door breaks gallery axis.',
        lightingMood: 'instrument_amber',
      },
      drum_lane: {
        label: 'Starboard lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Starboard deck lane; lateral pressure on relay.',
        lightingMood: 'water_reflection',
      },
      relay_cage: {
        label: 'Engine hatch cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature engine-room threshold cage; hull diagonal read.',
        lightingMood: 'engine_red_bias',
      },
      foreman_cage: {
        label: 'Bridge wing',
        intent: 'overwatch_pick',
        physicalIntent: 'Bridge wing glass down into engine hatch cage.',
        lightingMood: 'helm_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Teak stern reception; galley west, sun deck east, center companionway commit.' },
      west_service_connector: { physicalIntent: 'Galley service pocket; brass rail and low headroom.' },
      east_flank_connector: { physicalIntent: 'Sun deck approach compressed toward mid companionway door.' },
      mid_lane_center: { physicalIntent: 'Companionway spine; helm door read forward between zones.' },
      mid_lane_west: { physicalIntent: 'Port wedge before nav relay threshold.' },
      alarm_relay_room: { physicalIntent: 'Nav stack + alarm interconnect; offset door breaks gallery axis.' },
      drum_lane: { physicalIntent: 'Starboard deck lane; water reflection enfilade on relay.' },
      relay_cage: { physicalIntent: 'Engine hatch threshold cage; hull diagonal read.' },
      foreman_cage: { physicalIntent: 'Bridge wing glass down into engine hatch cage.' },
    },
  },
  8: {
    shellTieIn:
      'Lobby shell (layout 1): cold aisle / hot aisle kits and core vestibule reads inherit mirrored zone doors—commit racks on the flank the first door feeds or you will pinch against the swapped spawn column.',
    rooms: {
      dock_intake: {
        label: 'Cold aisle intake',
        intent: 'read_and_pick_route',
        physicalIntent: 'Cold aisle intake: PDU west, hot aisle east, center glass spine commit.',
        lightingMood: 'cold_aisle_blue',
      },
      west_service_connector: {
        label: 'PDU pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'PDU pocket; cable tray overhead rhythm.',
        lightingMood: 'rack_led_cool',
      },
      east_flank_connector: {
        label: 'Hot aisle approach',
        intent: 'flank_pressure',
        physicalIntent: 'Hot aisle compression toward mid containment.',
        lightingMood: 'hot_aisle_amber',
      },
      mid_lane_center: {
        label: 'Data hall spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Data hall spine between containment doors.',
        lightingMood: 'neutral_tile',
      },
      mid_lane_west: {
        label: 'Cross-connect wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Cross-connect wedge before ops relay.',
        lightingMood: 'fill_cool',
      },
      alarm_relay_room: {
        label: 'Ops relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Ops desk + hardened panel; offset door for enfilade break.',
        lightingMood: 'console_pulse',
      },
      drum_lane: {
        label: 'Trunking lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Overhead trunking lane; lateral flank on ops relay.',
        lightingMood: 'shadow_trunk',
      },
      relay_cage: {
        label: 'Core cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature core approach cage; glass enfilade read.',
        lightingMood: 'core_high_contrast',
      },
      foreman_cage: {
        label: 'SOC overlook',
        intent: 'overwatch_pick',
        physicalIntent: 'SOC glass overlook into core cage.',
        lightingMood: 'soc_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Cold aisle intake; PDU west, hot aisle east, center glass spine commit.' },
      west_service_connector: { physicalIntent: 'PDU pocket; cable tray overhead rhythm before ops relay.' },
      east_flank_connector: { physicalIntent: 'Hot aisle approach compressed toward mid containment.' },
      mid_lane_center: { physicalIntent: 'Data hall spine between containment doors.' },
      mid_lane_west: { physicalIntent: 'Cross-connect wedge before ops relay desk.' },
      alarm_relay_room: { physicalIntent: 'Ops desk + hardened panel; offset door for rack enfilade break.' },
      drum_lane: { physicalIntent: 'Overhead trunking lane; lateral flank on ops relay.' },
      relay_cage: { physicalIntent: 'Core approach cage; cold corridor and core vestibule kit.' },
      foreman_cage: { physicalIntent: 'SOC glass overlook into core cage.' },
    },
  },
  9: {
    shellTieIn:
      'Lobby shell (layout 1): customs yard and watchtower beats pick up mirrored thresholds—inspection pocket vs convoy lane pressure rotates with door geometry while the sand-axis spine and gate cage stay center-true.',
    rooms: {
      dock_intake: {
        label: 'Customs yard',
        intent: 'read_and_pick_route',
        physicalIntent: 'Desert customs yard: inspection west, convoy east, center sand axis commit.',
        lightingMood: 'harsh_sun_fill',
      },
      west_service_connector: {
        label: 'Inspection pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Inspection pocket; container shadow.',
        lightingMood: 'shade_cool',
      },
      east_flank_connector: {
        label: 'Convoy approach',
        intent: 'flank_pressure',
        physicalIntent: 'Convoy lane compression toward mid gate.',
        lightingMood: 'dust_amber',
      },
      mid_lane_center: {
        label: 'Checkpoint spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Checkpoint spine; tower sightline preview.',
        lightingMood: 'neutral_sand',
      },
      mid_lane_west: {
        label: 'Secondary wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Secondary wedge before tower relay.',
        lightingMood: 'fill_flat',
      },
      alarm_relay_room: {
        label: 'Tower relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Tower relay desk + panel; offset door breaks long axis.',
        lightingMood: 'beacon_pulse',
      },
      drum_lane: {
        label: 'Convoy flank lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Convoy flank lane; lateral pressure on relay.',
        lightingMood: 'heat_shimmer',
      },
      relay_cage: {
        label: 'Gate cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature gate cage before crossing threshold.',
        lightingMood: 'gate_hot_read',
      },
      foreman_cage: {
        label: 'Watchtower post',
        intent: 'overwatch_pick',
        physicalIntent: 'Watchtower post glass down into gate cage.',
        lightingMood: 'tower_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Desert customs yard; inspection west, convoy east, sand axis center commit.' },
      west_service_connector: { physicalIntent: 'Inspection pocket; container shadow before tower relay.' },
      east_flank_connector: { physicalIntent: 'Convoy lane compression toward mid gate door.' },
      mid_lane_center: { physicalIntent: 'Checkpoint spine; tower sightline preview downrange.' },
      mid_lane_west: { physicalIntent: 'Secondary wedge before tower relay threshold.' },
      alarm_relay_room: { physicalIntent: 'Tower relay desk + panel; offset door breaks long sand axis.' },
      drum_lane: { physicalIntent: 'Convoy flank lane; heat shimmer lateral pressure on relay.' },
      relay_cage: { physicalIntent: 'Gate cage before crossing threshold; customs booth kit.' },
      foreman_cage: { physicalIntent: 'Watchtower post glass down into gate cage.' },
    },
  },
  10: {
    shellTieIn:
      'Dock shell (layout 0): nave, crossing, and choir-loft verticality stay married to classic cargo-axis doors—sacristy relay and crossing glass reads remain symmetric to the unmirrored shell the glass kit was authored for.',
    rooms: {
      dock_intake: {
        label: 'Narthex',
        intent: 'read_and_pick_route',
        physicalIntent: 'Narthex nave read: chapel west, procession east, center candle axis commit.',
        lightingMood: 'candle_warm_haze',
      },
      west_service_connector: {
        label: 'Chapel pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Chapel pocket; stone niche rhythm.',
        lightingMood: 'niche_cool',
      },
      east_flank_connector: {
        label: 'Procession approach',
        intent: 'flank_pressure',
        physicalIntent: 'Procession approach compressed toward crossing door.',
        lightingMood: 'stained_edge',
      },
      mid_lane_center: {
        label: 'Crossing spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Crossing spine under vault implied read.',
        lightingMood: 'vault_neutral',
      },
      mid_lane_west: {
        label: 'Vestry wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Vestry wedge before sacristy relay.',
        lightingMood: 'wax_fill',
      },
      alarm_relay_room: {
        label: 'Sacristy relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Sacristy desk + bell panel; offset door breaks axis.',
        lightingMood: 'bell_soft_pulse',
      },
      drum_lane: {
        label: 'Colonnade lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Colonnade lane; lateral flank on sacristy.',
        lightingMood: 'column_shadow',
      },
      relay_cage: {
        label: 'Crossing cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature crossing cage before altar approach.',
        lightingMood: 'altar_hot_contrast',
      },
      foreman_cage: {
        label: 'Choir loft',
        intent: 'overwatch_pick',
        physicalIntent: 'Choir loft rail read down into crossing cage.',
        lightingMood: 'loft_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Narthex nave read; chapel west, procession east, candle axis center commit.' },
      west_service_connector: { physicalIntent: 'Chapel pocket; stone niche rhythm off nave bulkhead.' },
      east_flank_connector: { physicalIntent: 'Procession approach compressed toward crossing door.' },
      mid_lane_center: { physicalIntent: 'Crossing spine under vault implied read.' },
      mid_lane_west: { physicalIntent: 'Vestry wedge before sacristy relay.' },
      alarm_relay_room: { physicalIntent: 'Sacristy desk + bell panel; offset door breaks axis.' },
      drum_lane: { physicalIntent: 'Colonnade lane; lateral flank on sacristy.' },
      relay_cage: { physicalIntent: 'Crossing cage before altar approach; altar glass kit.' },
      foreman_cage: { physicalIntent: 'Choir loft rail read down into crossing cage.' },
    },
  },
  11: {
    shellTieIn:
      'Lobby shell (layout 1): deck intake and engine companionway inherit mirrored zone doors—stores vs winch first-contact pressure swaps with the shell while the hull cage and bridge overlook remain the authored payoff.',
    rooms: {
      dock_intake: {
        label: 'Deck intake',
        intent: 'read_and_pick_route',
        physicalIntent: 'Steel deck intake: stores west, winch east, center hatch commit.',
        lightingMood: 'industrial_sodium',
      },
      west_service_connector: {
        label: 'Stores pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Stores pocket; chain locker rhythm.',
        lightingMood: 'hold_cool',
      },
      east_flank_connector: {
        label: 'Winch approach',
        intent: 'flank_pressure',
        physicalIntent: 'Winch deck compression toward mid bulkhead.',
        lightingMood: 'rust_edge',
      },
      mid_lane_center: {
        label: 'Deck spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Deck spine between watertight doors.',
        lightingMood: 'steel_neutral',
      },
      mid_lane_west: {
        label: 'Port wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Port wedge before engine relay.',
        lightingMood: 'bilge_fill',
      },
      alarm_relay_room: {
        label: 'Engine relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Engineer relay + shutdown panel; offset door.',
        lightingMood: 'alarm_orange',
      },
      drum_lane: {
        label: 'Starboard lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Starboard equipment lane; lateral flank on relay.',
        lightingMood: 'shadow_hull',
      },
      relay_cage: {
        label: 'Engine room cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature engine room threshold cage.',
        lightingMood: 'machinery_hot',
      },
      foreman_cage: {
        label: 'Bridge access',
        intent: 'overwatch_pick',
        physicalIntent: 'Bridge access overlook into engine cage.',
        lightingMood: 'bridge_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Steel deck intake; stores west, winch east, center hatch commit.' },
      west_service_connector: { physicalIntent: 'Stores pocket; chain locker rhythm before engine relay.' },
      east_flank_connector: { physicalIntent: 'Winch deck compression toward mid bulkhead door.' },
      mid_lane_center: { physicalIntent: 'Deck spine between watertight doors.' },
      mid_lane_west: { physicalIntent: 'Port wedge before engineer relay threshold.' },
      alarm_relay_room: { physicalIntent: 'Engineer relay + shutdown panel; offset door for companionway pinch.' },
      drum_lane: { physicalIntent: 'Starboard equipment lane; hull shadow lateral flank.' },
      relay_cage: { physicalIntent: 'Engine room threshold cage; hold peek glass kit.' },
      foreman_cage: { physicalIntent: 'Bridge access overlook into engine cage.' },
    },
  },
  12: {
    shellTieIn:
      'Dock shell (layout 0): sky lobby glass, board corridor, and helipad vestibule stay aligned with classic cargo-axis doors—apex vault and crown relay reads stay consistent with the unmirrored sequence identity paint.',
    rooms: {
      dock_intake: {
        label: 'Sky lobby',
        intent: 'read_and_pick_route',
        physicalIntent: 'Sky lobby over city grid: express west, service east, glass center commit.',
        lightingMood: 'city_bounce_fill',
      },
      west_service_connector: {
        label: 'Express pocket',
        intent: 'flank_or_delay',
        physicalIntent: 'Express elevator pocket; brushed steel rhythm.',
        lightingMood: 'cool_metal',
      },
      east_flank_connector: {
        label: 'Service approach',
        intent: 'flank_pressure',
        physicalIntent: 'Service shaft compression toward mid security.',
        lightingMood: 'shaft_amber',
      },
      mid_lane_center: {
        label: 'Glass spine',
        intent: 'commit_or_rotate',
        physicalIntent: 'Glass spine between zone doors; vertigo implied.',
        lightingMood: 'neutral_high_key',
      },
      mid_lane_west: {
        label: 'Security wedge',
        intent: 'threshold_fight',
        physicalIntent: 'Security wedge before crown relay.',
        lightingMood: 'soft_fill',
      },
      alarm_relay_room: {
        label: 'Crown relay',
        intent: 'objective_and_hold',
        physicalIntent: 'Crown security desk + panel; offset door breaks glass axis.',
        lightingMood: 'panel_pulse',
      },
      drum_lane: {
        label: 'Mullion lane',
        intent: 'flank_enfilade',
        physicalIntent: 'Mullion lane; lateral flank on crown relay.',
        lightingMood: 'sky_reflection',
      },
      relay_cage: {
        label: 'Helipad threshold cage',
        intent: 'signature_arena',
        physicalIntent: 'Signature helipad threshold cage; crown glass read.',
        lightingMood: 'apex_high_contrast',
      },
      foreman_cage: {
        label: 'Crown office',
        intent: 'overwatch_pick',
        physicalIntent: 'Crown office overlook into helipad cage.',
        lightingMood: 'executive_warm',
      },
    },
    floorplanSpaces: {
      dock_intake: { physicalIntent: 'Sky lobby over city grid; express west, service east, glass center commit.' },
      west_service_connector: { physicalIntent: 'Express elevator pocket; brushed steel rhythm.' },
      east_flank_connector: { physicalIntent: 'Service shaft compression toward mid security door.' },
      mid_lane_center: { physicalIntent: 'Glass spine between zone doors; vertigo implied.' },
      mid_lane_west: { physicalIntent: 'Security wedge before crown relay.' },
      alarm_relay_room: { physicalIntent: 'Crown security desk + panel; offset door breaks glass axis.' },
      drum_lane: { physicalIntent: 'Mullion lane; sky reflection lateral flank on crown relay.' },
      relay_cage: { physicalIntent: 'Helipad threshold cage; crown glass and helipad vest kit.' },
      foreman_cage: { physicalIntent: 'Crown office overlook into helipad cage.' },
    },
  },
};
